/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PragmaNumber {
    /**
    * Property data.
    */
    'property': any;
  }
}

declare global {


  interface HTMLPragmaNumberElement extends Components.PragmaNumber, HTMLStencilElement {}
  const HTMLPragmaNumberElement: {
    prototype: HTMLPragmaNumberElement;
    new (): HTMLPragmaNumberElement;
  };
  interface HTMLElementTagNameMap {
    'pragma-number': HTMLPragmaNumberElement;
  }
}

declare namespace LocalJSX {
  interface PragmaNumber {
    /**
    * Property data.
    */
    'property'?: any;
  }

  interface IntrinsicElements {
    'pragma-number': PragmaNumber;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pragma-number': LocalJSX.PragmaNumber & JSXBase.HTMLAttributes<HTMLPragmaNumberElement>;
    }
  }
}


