/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PragmaNumber {
    /**
    * Whether the field is disabled.
    */
    'disabled': boolean;
    /**
    * Pragma field data as a single object.  Setting this property will overwrite corresponding attributes.
    */
    'fieldAttribute': object|string;
    /**
    * The field's label.
    */
    'label': string;
    /**
    * The maximum value constraint.
    */
    'max': number;
    /**
    * The minimum value constraint.
    */
    'min': number;
    /**
    * The field's path.
    */
    'path': string;
    /**
    * The value step.
    */
    'step': number;
    /**
    * The field's value.
    */
    'value': number;
  }
}

declare global {


  interface HTMLPragmaNumberElement extends Components.PragmaNumber, HTMLStencilElement {}
  const HTMLPragmaNumberElement: {
    prototype: HTMLPragmaNumberElement;
    new (): HTMLPragmaNumberElement;
  };
  interface HTMLElementTagNameMap {
    'pragma-number': HTMLPragmaNumberElement;
  }
}

declare namespace LocalJSX {
  interface PragmaNumber {
    /**
    * Whether the field is disabled.
    */
    'disabled'?: boolean;
    /**
    * Pragma field data as a single object.  Setting this property will overwrite corresponding attributes.
    */
    'fieldAttribute'?: object|string;
    /**
    * The field's label.
    */
    'label'?: string;
    /**
    * The maximum value constraint.
    */
    'max'?: number;
    /**
    * The minimum value constraint.
    */
    'min'?: number;
    /**
    * The field's path.
    */
    'path'?: string;
    /**
    * The value step.
    */
    'step'?: number;
    /**
    * The field's value.
    */
    'value'?: number;
  }

  interface IntrinsicElements {
    'pragma-number': PragmaNumber;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pragma-number': LocalJSX.PragmaNumber & JSXBase.HTMLAttributes<HTMLPragmaNumberElement>;
    }
  }
}


